### ISSUE TITLE
Make mock-data generator from sample data.

### ISSUE THREAD

**Issue by abhishekmaha23** [bebbi/taloc-loader#1]
Intro task
- Make mock-data generator for end-to-end testing.
- Use faker library

**Comment by abhishekmaha23** [comment]
Initial approach
From my understanding of the code and the flow of it, I've found that the following files are needed for a full run

1. atmosfair: CSV file. Response Test Data.
2. legs: spesen and airplus: 2 XLSX files with same columns, different data.
3. legs: bta: 1 XLSX file with specific columns.'
4. HR: excerpts: 2 Different XLSX file formats (one till 2018, one after 2018).

An initial bank of people and flights taken has to be generated.
Based on these, multiple test-cases might arise.
1. All the people in the HR data are available in the legs data
2. Some people are different (either available in HR only or vice versa)
3. Some people have slightly different name spellings/name formats/ reversal of names (to test the hr name string matching)
4. Atmosfair data not being available for some flights (I'm unclear about the logic here)

To populate this data, I've made certain empty base files with only columns available
1. atmosfair-base.csv
2. bta-legs-base.xlsx
3. hr-after-2018-base.xlsx
4. hr-till-2018-base.xlsx
5. spesen-airplus-legs-base.xlsx

For each test run, I intend to generate a bank of names of people from different departments and ranges of values.
For each numerical column in these files, I'm currently manually determining a range of values and then will use a generator to yield random values in that range for that column.
For flight values, I intend to generate a bank of random trips between all possible airports, and then randomly assign them to people from the people bank.

Each test run will then generate a certain amount of data, write them into the XLSX and CSV files, and then perform the run.

**Comment by bebbi** [comment]
Overall this sounds good. I'm adding comments for minor tweaks of understanding.

- HR lists contain all employees (snapshot per given year), of which usually only a fraction flies, probably never 100%. This is relevant for the calculation of the per-FTE emissions of each department which is a future feature that has partially been started.
- A hr_bta_matches excel file is also always required whenever length(bta) > 0 (for the matching you indicate above). It is the required link between bta dataset (pax names only, possibly in different spelling, no employee ids) and HR list. This list of matches is created by the app in one run, then confirmed by user in the next (1 match proposed for EACH pax even if only low similarity found), and user then confirms or rejects the match.
- It's possible in all leg data that someone is a guest
  - in archive/airplus, those have no employee id
  - in bta, no difference is seen. Only the manually filled hr_bta_match distinguishes NN (not a match, is a guest) and NR (not a match, but raise an issue that it is an employee with missing HR record) establishes the difference

atmosfair example:
5 legs given, 3 have a match in atmosfair response.
This creates a new atmosfair data request (a csv also) containing 2 legs with no emission data.
(It normalizes, so if the two legs are the same flight, there is only 1 row in the atmosfair request)

Then this request is sent to atmosfair, and response is added into the atmosfair response folder.
Next run: 5 legs given, 5 have a match in atmosfair 2 response files.
