### ISSUE TITLE
Setup end-to-end tests

### ISSUE THREAD

**Issue by abhishekmaha23** [bebbi/taloc-loader#2]
Intro task
(#1 - to be finished first)
- Use mock data generators to set up test-cases 
- Integrate with existing flow of program to work independently/alongside

**Comment by abhishekmaha23** [comment]
After finishing up the mock data generator #1, I built 5 test cases based on our discussion before.
Essentially, I set the overall goals to be-
1. Verify that airports.json, anon-legs.json and legs_archive_timestamp.excel are created. (Verifying basic flow)
2. When there's any data in the BTA file, verify that hr_bta_matches file is created with the right 
  number of records (the right number of passengers who were present in the BTA records).
3. When hr_bta_matches is placed in the data folder, and NR/ NN are mentioned instead of Y, verify that the 
  hr_issue_list.xlsx is created with the right number of  records 
4. Verify that when atmosfair data is missing for the right number of trips, the to_atmosfair.csv is populated with 
  the right number of flight segments (sum of all segments of missing trips from the configuration) 

With this in mind, the 5 test cases were :
- Case 1 - Comprehensive use-case with all types of data. Basically checking the flow and errors with normal data.
- Case 2 - Ideal use case. All people who flew are in the HR files. Complete Atmosfair coverage.
- Case 3 - Edge case. All people present in the BTA leg data. Reducing complication by having complete Atmosfair (as much as possible). 
-- It turns out that setting mock data for all the created flight segments in atmosfair_response.csv still causes the app to say that it needs more data. I'm not sure if I understand this
- Case 4 - Edge-case. Ideally distributed people data (minimal BTA). Empty Atmosfair data.
- Case 5 - Same as Case 1. Here, we can manually verify the contents of hr_bta_matches, to_atmosfair and hr_issue_list (with a second run on the same data).

The code is ready, and has been committed to a new branch!

**Comment by abhishekmaha23** [comment]
Some issues that I noticed already from running the edge cases

1. This happens sometimes with normal distributed dataset ( I'm not sure why - does this represent that there's a duplicate within a single flight?)
    -- Unexpected error: airport_info has duplicate iata codes YTY
2. BTA_legs_import cannot handle empty data files.
    -- AttributeError: Can only use .dt accessor with datetimelike values
4. regular_legs_import cannot handle empty spesen or airplus data files.
    -- ValueError: Wrong number of items passed 15, placement implies 1
5. atmosfair_response csv cannot handle empty data.
    -- Exception: No columns to parse from file

**Comment by bebbi** [comment]
Regarding your issues/questions:
- Case 3 issue (previous comment): does "needs more data" refer to it creating an `to_atmosfair.csv` file? In this case, are the segments listed in `to_atmosfair` present in the `bta_legs` file, and are they present in the `atmosfair_response.py`?
- duplicate iata codes YTY: So airports.json is essentially a copy of the airports csv in assets/, however minimized to just contain the entries present in legs. The error means that the assets file has a duplicate definition for YTY, I pushed a commit removing this, and it shouldn't occur any longer (rebase time :) )
- issues 2-4: Agree, these would be good to handle gracefully as part of the code clean-up!

**Comment by bebbi** [comment]
Another item I just thought of that we could watch for when modeling e2e:
It happens that multiple people fly the same flight.
This means multiple rows of legs with all flight details being the same, class, date, destination etc. .
In this case you can have `n` leg rows but `n - duplicates` atmosfair request (and response) rows. We might have chatted about this already.

**Comment by abhishekmaha23** [comment]
I hadn't verified that the segments were specifically in the bta_legs file! But they're definitely present in one of the 3 legs files - and also in the atmosfair_response csv file. I'll run a more manual test to verify this case 

> * Case 3 issue (previous comment): does "needs more data" refer to it creating an `to_atmosfair.csv` file? In this case, are the segments listed in `to_atmosfair` present in the `bta_legs` file, and are they present in the `atmosfair_response.py`?

**Comment by abhishekmaha23** [comment]
> Another item I just thought of that we could watch for when modeling e2e:
> It happens that multiple people fly the same flight.
> This means multiple rows of legs with all flight details being the same, class, date, destination etc. .
> In this case you can have `n` leg rows but `n - duplicates` atmosfair request (and response) rows. We might have chatted about this already.

I believe we'd have to add this case also in the mock_data_generator file - we're not creating passengers for pre-existing flights at the moment! This case could be an individual issue, I believe - is it handled currently in the app?

**Comment by abhishekmaha23** [comment]
> I hadn't verified that the segments were specifically in the bta_legs file! But they're definitely present in one of the 3 legs files - and also in the atmosfair_response csv file. I'll run a more manual test to verify this case

I figured it out - I had missed the dict 'bta_fare_class_map' which was converting the travel classes to the atmosfair values. Fixing it now and the matching works as expected again.

**Comment by bebbi** [comment]
> I believe we'd have to add this case also in the mock_data_generator file - we're not creating passengers for pre-existing flights at the moment! This case could be an individual issue, I believe - is it handled currently in the app?

Yes, a new issue will do fine.
Yes, this case is handled in the app because if you think about atmosfair: The atmosfair cache acts as a lookup for emission data for any given flight. So in the atmosfair cache I have taken care to only register unique flights, as duplicates could lead to hard-to-debug issues.
And in consequence, the atmosfair cache tends to have less rows than the sum of all legs.
