### ISSUE TITLE
Create hand-over instructions

### ISSUE THREAD

**Issue by bebbi** [bebbi/taloc-loader#22]
The customer is on windows, like you! That's an advantage.

We need a short google doc with instructions for a non-developer but computer-savvy person to
- install docker on windows
- install our code - ideally directly from github if that's easy enough in windows
- add data
- run docker-compose
- find the outputs

**Comment by bebbi** [comment]
Need to deal with config.yml, please see also closed #16.

A simple solution could be providing a `config.yml.template` file in versioning control?

**Comment by bebbi** [comment]
On hold until config.yml and doc input method finalized/simplified (local web server submit?).

**Comment by bebbi** [comment]
@abhishekmaha23 Thanks for https://docs.google.com/document/d/1U4XMHj53QZ3jU3ylR2o_1DGt6IShe9YSVgkTn817XSU/edit !

Minor feedback:
- Can you remove the section for "with git" and default to "no git"/zip file section only?
- Is there a way to use it on Windows without VS Code which we could use instead of the VS Code?

E.g. in MacOS, I can run it using a regular shell ("docker compose up").
Do we have a windows way of starting it without VS Code? E.g. via a shell or via docker desktop functionality?

**Comment by abhishekmaha23** [comment]
I've updated the document with the related details!
