### ISSUE TITLE
Restructure and cleaning of code.

### ISSUE THREAD

**Issue by abhishekmaha23** [bebbi/taloc-loader#4]
Goals
- Rearchitect flow of entire project under DRY principles and general project building principles (Following principles in https://docs.python-guide.org/writing/structure/). (Intended purpose to detach from VS Code running flow, and to allow quick check/testing, which should become easier when #1 is completed.)
- Integrate tests and debug flow to work under redesign
- Implement logging (probably saved to file, along with run ids), with it being possible to rerun on an a previous run ID with updated data files.
- Clean up comments and identify all TO-DOs as issues. 

Notes
- Testing should pass at all times, and both E2E and Unit Tests need to be designed beforehand to ensure no break in functionality.
- Might be safer to install pandas directly on the official python-slim image

**Comment by bebbi** [comment]
What is the use-case for re-running with a previous run ID and updated data files?

**Comment by abhishekmaha23** [comment]
> What is the use-case for re-running with a previous run ID and updated data files?

I'd misunderstood! I thought the rerun with hr_bta_matches would be try not to redo any of the previous matching, and would append results- similarly with updated data from atmosfair responses
I would like to remove redundant running here if possible..

**Comment by abhishekmaha23** [comment]
Tentative actions (slightly more atomic)

1. Separate code functionality by data source, isolate utility functions and core methods and reorganize (also exploring different flow of program for redundancy) (6-8 hours)
2. Convert app.py call and other code calls into method calls rather than file imports (would ensure modularity and help with debugs) (5 hours)
3. Implement logging, documentation of functionality (4 hours)
4. Clean up Docker build and dependencies (1 hour)
5. Clean up data gathering, remove manual entry into config.yml - (would solve part of #7) (3 hours)
6. Ensure working with previous E2E tests and mock data (1- 2 hours - continuously checking while implementing other steps)

Estimated time - (~20-24 hours)

**Comment by bebbi** [comment]
OK great. Lets agree on the approach with the points before moving ahead.

1. Yes, isolation is helpful.
Let's define the output of "explore different flows", or analyze a bit more here:
The current pattern is that only one app is ever run, but it produces different outputs depending on the inputs (and input completeness). This takes away the burden from user to manage state (or work with separate apps).

> I would like to remove redundant running here if possible.
I may misunderstand, I don't think we have redundant runs. As examples:
- we need to create a "atmosfair request" file in one run, to send it to the service and pass the response to a second run)
- the name matcher needs human confirmation, so it needs to create proposals in a first run, then consider the human decisions about the proposal in a second run.

On the contrary, since the app gathers all types of data in parallel, above results in 2, not 4 total runs.
Maybe you can detail your idea a bit more?

2. Let me reformulate so I am sure I understand: module logic is executed when calling imported functions, not at the time of importing, correct? That would be great.
3. ok
4. I suppose you mean moving pandas etc. out of docker image and into requirements? That sounds good. Anything else? 
5. That would be nice, let's review your approach here.
6. ok

**Comment by abhishekmaha23** [comment]
1. Ah, I didn't mean direct redundancy - the app is definitely removing the burden of state and centralizing the functionality!
I was just wondering if there's maybe a way to smoothen the flow a little -
 - When the user gets information about needing to verify hr_bta_matches, the modified hr_bta_matches file is placed in the data-originals folder again, and the program reads through all the original data again. There's also output placed in the folder - anon-legs.json and legs-archive.xlsx are created in the first run itself, and then in the second run, another leg-archive.xlsx is created- so I suggested that a run ID might help connect the two runs, append the new data to the same file, delete the CSV caches that were generated for the overall sequence of runs. I really need to explore this a bit better, I could be mistaken about the code flow!
 - In a UI (through a browser), perhaps we could hold the state of the program, allow the user to verify matches, fix HR issues directly and then continue run, it's definitely harder to get user input from the terminal (I think the Docker abstraction might make it quite impossible)
 2. Yeah! Currently, initialization data like airport data is being read at the time of importing, and I'd like to change this to a more intentional importing..
 4. I don't think so! I'll mildly explore bringing the versions of the libraries to the latest version if it doesn't break anything, but not a high priority!
 5. Currently, I was hoping to explore these options - but I'll try to come up with more!
 - Creating code and a folder structure to read all the files within a subdirectory in the parent folder, without having to specify all the filenames in the config each time
 - Create archival data folders (cleaning up after a full successful run, either deleting or moving data that has been processed)

**Comment by bebbi** [comment]
I think in your answer 3->4, 4->5, then:

1.
- Just to clarify, currently, the hr_bta_matches (proposal aka "request for manual review") is placed in the output/ folder. User will have to complete then place in the input folder.
- Yes, the output/ folder could (should) be emptied on start of every app run, it would result in no difference to running behaviour. The app fully works with "cumulative data-sets" and doesn't depend on previous runs. (Any app output goes to `output/`, none goes to the `data-originals` folder. csv caches are an exception which we should either fix or just remove.
- Note it's likely that input legs are edited, removed, added between runs
- Yes, a browser UI sounds like a neat solution if it makes sense to upgrade to this from a cost perspective. We can check later if even some of the cleaning/fixing interactions should happen online.
- yes, docker will be ok for the ca August roll-out of this tool, but not a good option to become more user friendly. However, even starting a web server or even running a python script won't be much user friendlier either. Perhaps there are simple frameworks to converting web servers into native apps, or other ideas? This is interesting but low prio.

5.
- I just received the customers manual extension of HR records for each year: everything in one xlsx, one sheet per year. I think it's not too bad like this, but how do we address individual sheet names in xls files if not with a config file or a web app?
- Would deleting the output/ on start of every program run already be a start?

**Comment by abhishekmaha23** [comment]
- I've added a method to reset the project in the e2e_tests.py file - It clears the cached data and the output folder (and also the data folder - meant to clear test data, but can be prevented)
- Regarding addressing individual sheet names, would there be many cases in which multiple sheets are present in a single file?
By default, the first sheet is usually picked by Pandas.
- Starting the webserver could be really simple with a shell script or so! But in case you feel a GUI would be better received, there's a number of GUI options which would be very simple to set up rapidly - Kivy or Tkinter. Plugging in the backend app would be minimal effort!

**Comment by abhishekmaha23** [comment]
Proposing the action items for the second milestone- this entire issue! 
From before - 

1. Separate code functionality by data source, isolate utility functions and core methods and reorganize (8 hours)
2. Convert app.py call and other code calls into method calls rather than file imports (would ensure modularity and help with debugs) Verify that the debug functionality with VSCode is usable and works! (5 hours).
3. Implement logging (with run IDs, log files and log levels), documentation of functionality (4 hours)
4. Clean up Docker build and dependencies (1 hour)
5. Clean up data gathering, remove manual entry into config.yml  - (3 hours)
 -- Separate runs into multiple types (production server use, debug mode with VS Code, testing mode for E2E and unit tests)
6. Ensure working with previous E2E tests and mock data (2 hours - continuously checking while implementing other steps)
7. Buffer time for reviews, modifications and other issues! (1-2 hours)

Estimated time - (~24 hours)
